### ISSUE TITLE
[S1 - PBI2] Membuat halaman Login

### ISSUE THREAD

**Issue by 4rnots** [SI-RPL-2023/SI4403_A_Farm.io#4]

**Comment by rafidfadhil** [comment]
Halaman login adalah sebuah halaman web yang dirancang untuk memungkinkan pengguna masuk ke dalam sistem atau layanan tertentu dengan memasukkan kredensial yang diperlukan, seperti nama pengguna dan kata sandi. 

Halaman login umumnya memiliki dua bidang input untuk memasukkan informasi kredensial, yaitu bidang untuk memasukkan nama pengguna atau alamat email dan bidang untuk memasukkan kata sandi. Beberapa halaman login juga dapat memiliki fitur tambahan, seperti pilihan untuk mengingat kredensial pengguna atau mengatur ulang kata sandi jika lupa.

Halaman login biasanya terlindungi dengan keamanan tambahan, seperti enkripsi SSL, dan seringkali memiliki tindakan keamanan lainnya, seperti verifikasi dua faktor, untuk melindungi akun pengguna dari akses yang tidak sah.

Mockup Login

![Image](https://user-images.githubusercontent.com/100100825/228784004-ff59f6e0-9145-4892-a28b-4be8f0a3c0f5.png)
